version: '2'
services:
    flaskapp-frontend:
        build: .
        container_name: flaskapp-frontend
        networks:
            - esnet
        environment:
            - FLASK_CONFIGURATION=frontend
            - debug:debug1
        ports:
            - 10000:80
        restart: always
        external_links:
            - mongo
            - mongo1
            - mongo2
            - elastic:elasticsearch

networks:
  esnet:
    driver: bridge
