version: '2'
services:
    flaskapp:
        image: exiasr/alpine-flask:latest
        container_name: flaskapp
        networks:
            - esnet
        ports:
            - "5000:80"
        volumes:
            - .:/home/app
        environment:
            - FLASK_CONFIGURATION=deploy
            - debug:debug1
        restart: always
        links:
            - mongo
            - mongo1
            - mongo2
            - elastic:elasticsearch
    mongo:
        image: mongo:3.4.1
        container_name: mongo
        command: mongod --replSet mongo-replica
        networks:
            - esnet
        volumes:
            - esdata:/data/db
        ports:
            - 27017:27017
        links:
          - mongo1:mongo1
          - mongo2:mongo2
    mongo1:
        image: mongo:3.4.1
        container_name: mongo1
        command: mongod --replSet mongo-replica
        networks:
            - esnet
        volumes:
            - mongo-replica1:/data/db
        ports:
            - 30000:27017
    mongo2:
        image: mongo:3.4.1
        container_name: mongo2
        command: mongod --replSet mongo-replica
        networks:
            - esnet
        volumes:
            - mongo-replica2:/data/db
        ports:
            - 30001:27017
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.1.2
        container_name: elastic
        ports:
            - 9200:9200
        volumes:
            - elastic-data:/usr/share/elasticsearch/data
        networks:
            - esnet
        environment:
            - http.host=0.0.0.0
            - transport.host=127.0.0.1
            - cluster.name=collabrative_list_docker_cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        mem_limit: 1g
        cap_add:
            - IPC_LOCK
    kibana:
        image: docker.elastic.co/kibana/kibana:5.1.2
        container_name: kibana
        ports:
            - 5601:5601
        networks:
            - esnet
        environment:
            - ELASTICSEARCH_PASSWORD=changeme
            - ELASTICSEARCH_USERNAME=elastic
        links:
            - elastic:elasticsearch

networks:
  esnet:
    driver: bridge

volumes:
    esdata:
        driver: local
    mongo-replica1:
        driver: local
    mongo-replica2:
        driver: local
    elastic-data:
        driver: local